[package]
name = "rv-runtime-test"
version = "0.1.0"
edition = "2021"

[build-dependencies]
rv-runtime-generator = { path = "../rv-runtime-generator" }

[dependencies]
log = "*"
lazy_static = { version = "*", features = ["spin_no_std"] }
spin = "*"
